config/routes.rb
Bshakr::Application.routes.draw do
  root :to => "main#home"

  devise_for :users

  resources :posts
  get 'about' => 'main#about', as: 'about'
  match '(errors)/:status', to: 'errors#show', constraints: {status: /\d{3}/} , via: :all
  get 'work/solace' => 'work#solace', as: 'solace'
  get 'work/stourvalley' => 'work#stourvalley', as: 'stourvalley'
  get 'work/nooun' => 'work#nooun', as: 'nooun'
  get 'work/nyexpo' => 'work#nyexpo', as: 'nyexpo'
  get 'work/lawfirm' => 'work#lawfirm', as: 'lawfirm'
  get 'work/egyptolution'	=> 'work#egyptolution', as: 'egyptolution'
  get 'work/appommunity'	=> 'work#appommunity', as: 'appommunity'
  get 'work/tia'	=> 'work#tia', as: 'tia'
	get 'work/' => 'work#index', as: 'work'  

  namespace :admin do
  	root :to => 'posts#index'
  	resources :posts
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates_presence_of :title, :content, :published_at
  validates :slug, uniqueness: true, presence: true
  before_validation :generate_slug
  
  #defines the database field to be used in the url paramater
  def to_param
  	slug
  end
  
  def generate_slug
  	self.slug ||= title.parameterize
  end
  
  def render_html
    options = {
      no_intra_emphasis: true,
      tables: true,
      fenced_code_blocks: true,
      autolink: true,
      strikethrough: true,
      space_after_headers: true,
      superscript: true
    }
    markdown = Redcarpet::Markdown.new(Bshakr::MarkdownRenderer, options)
    markdown.render(self.content).html_safe
  end

  def self.search(search)
  	if search
  		where('title LIKE ?', "%#{search}%")
  	else
  		unscoped
  	end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  include Gravtastic
  gravtastic
  
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  

  # Setup accessible (or protected) attributes for your model
  #attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < AdminController
	before_filter :authenticate_user!
	before_filter :find_post, only: [:show, :edit, :update, :destroy]
	helper_method :sort_column, :sort_direction
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.search(params[:search]).order(sort_column + " " + sort_direction).page(params[:page]).per(5)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to admin_posts_url, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update

    respond_to do |format|
      if @post.update_attributes(post_params)
        format.html { redirect_to admin_posts_url, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to admin_posts_url , notice: 'Post was successfully deleted.'}
      format.json { head :no_content }
    end
  end
private
  def post_params
    params.require(:post).permit(:title, :content, :published_at, :slug)
  end

  def find_post
  	@post = Post.find_by_slug!(params[:id])
  end
  def sort_column
  	Post.column_names.include?(params[:sort]) ? params[:sort] : "id"
  end
  def sort_direction
  	%w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	before_filter :authenticate_user!
	layout 'admin'
	
	def index
		redirect_to admin_posts_url
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def show
    render action: request.path[1..-1]
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def home
	  @posts = Post.where("published_at <= ?", Time.now).order("published_at DESC")
  end
  
  def about
    @instagram = Instagram.user_recent_media("4352736", {:count => 6})
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  respond_to :html, :xml, :json, :atom
  def index
	  @posts = Post.where("published_at <= ?", Time.now).order("published_at DESC")
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  	@post = Post.find_by_slug!(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end
end

app/controllers/work_controller.rb
class WorkController < ApplicationController

	def index
	end
  def stourvalley
  end
	def solace
	end

	def nooun
	end

	def nyexpo
	end
	
	def lawfirm
	end
	
	def egyptolution
	end
	
	def appommunity
	end

	def tia
	end
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
	def sortable(title, column)
		direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
		css_class = column == sort_column ? "current #{sort_direction}" : nil
		link_to title, params.merge( :sort => column, :direction => direction, :page => nil), {:class => css_class}
	end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def post_published_time post
    post.published_at.to_time.strftime('%B %e, %Y')
  end
end

app/views/admin/posts/_form.html.erb
<%= simple_form_for [:admin, @post], :html => { :class => 'form-horizontal' } do |f| %>
      <%= f.error_notification %>
      <%= f.input :title ,:input_html => { :class => "span8" }%>
			<%= f.input :published_at,:as => 'string', :input_html => { :value => @post.published_at, "data-date-format" => "yyyy-mm-dd", :class => "datepicker" }%>
      <%= f.input :content, :input_html => { :class => "span8 textarea-big" } %>

  <div class="form-actions">
    <%= f.button :submit,  :class => ' btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                admin_posts_path, :class => 'btn' %>
  </div>
<% end %>

app/views/admin/posts/edit.html.erb
<%- model_class = Post -%>
<div class="container">
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>
</div>

app/views/admin/posts/index.html.erb
<%- model_class = Post -%>
<div class="container">
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %> Management</h1> 
</div>
<div class="well">
<div class="row">
<div class="span6 ">
	<%= form_tag admin_posts_path, :method => 'get', :class => 'form-inline' do %>	
		<%= hidden_field_tag :direction, params[:direction] %>		
		<%= hidden_field_tag :sort, params[:sort] %>
		<div class="input-append">
	
			<%= text_field_tag :search %>
			<%= submit_tag "search", :class => "btn" %>
		</div>
	<% end %>
</div>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= sortable model_class.human_attribute_name(:id),  "id"%></th>
      <th><%= sortable model_class.human_attribute_name(:title), "title" %></th>
      <th><%= sortable model_class.human_attribute_name(:created_at), "created_at" %></th>
      <th>Published</th>

      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= link_to post.id, post_path(post) %></td>
        <td><%= post.title %></td>
        <td><%=l post.created_at , :format => :long%></td>
				<td>
					<% if post.published_at %>
						<%if post.published_at <= Time.now %>
							<span class="label label-inverse">Published</span>
						<%else %>
							<span class="label label-important"> Not Published</span>
						<%end%>
					<% end%>
				</td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_admin_post_path(post), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      admin_post_path(post),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", 
						  									:default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="form-actions">
  <%= paginate @posts, :theme => 'twitter-bootstrap'%>

	<%= link_to t('.new', :default => t("helpers.links.new")),
	        new_admin_post_path,
	        :class => 'btn btn-primary' %>
</div><!--form-actions -->
</div><!-- well -->
</div><!-- container -->

app/views/admin/posts/new.html.erb
<%- model_class = Post -%>
<div class="container">
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>
</div>

app/views/admin/posts/show.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @post.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:content) %>:</strong></dt>
  <dd><%= @post.render_html %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              posts_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_post_path(@post), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              post_path(@post),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/layouts/_footer.html.erb
<footer>
	<p>Copyright © 2013 <%= link_to 'Bassem Shaker', root_url %>. All Rights Reserved</p>
</footer>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bassem Shaker</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>

  <%= csrf_meta_tags %>
  <script type="text/javascript" src="http://use.typekit.com/rbx6ljz.js"></script><script type="text/javascript">try{Typekit.load();}catch(e){}</script>

  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<div class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<a class="brand" href="#">Bassem Shaker</a>
			<div class="login-area">
			<% if user_signed_in? %>
				<%= link_to "Logout", destroy_user_session_path, method: :delete, :class => "logout-link" %>
				<%= image_tag current_user.gravatar_url, :class => "gravatar" %>

			<% else %>
				<%= link_to "Login", new_user_session_path %>
			<% end %>
			</div>
		</div>
	</div>
</div>
<div class="container">
<% flash.each do |name, msg| %>
	<div class="animated bounceInDown alert alert-<%= name == :notice ? "success" : "error" %>">
		<button type="button" class="close" data-dismiss="alert">&times;</button>
		<%= msg %>
	</div>
<% end %>
</div>

<%= yield %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Bassem Shaker</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <meta name="application-name" content="Bassem Shaker">
  <meta name="author" content="Bassem Shaker">
  <meta name="description" content="The Portfolio and Blog of Bassem Shaker">
  <meta name="keywords" content="Bassem Shaker, Bassem, Shaker, Freelance, UK Freelancer, Designer, Developer">
  <meta name="robots" content="follow, all" />

  <link rel="canonical" href="http://bassemshaker.com/" />
  <link rel="me" href="http://twitter.com/bshakr" />

  <meta property="og:site_name" content="bassemshaker.com" />  
  <meta property="og:title" content="bassemshaker.com" />
  <meta property="og:description" content="The blog of Bassem Shaker" />  
  <meta property="og:type" content="website" />
  <meta property="og:url" content="http://bassemshaker.com/" />

  <script type="text/javascript" src="//use.typekit.net/rbx6ljz.js"></script>
	<script type="text/javascript">try{Typekit.load();}catch(e){}</script>
  <%= yield :head %>

</head>
<body>
<div class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<%= link_to 'Bassem Shaker', root_url, :class => 'brand' %></a>
			<div class="nav-collapse pull-right">
				<ul class="nav">
					<li><%= link_to 'work', work_url %></li>
					<li><%= link_to 'blog', posts_url %></li>
					<li><%= link_to 'about', about_url %></li>
					
				</ul>
			</div>
		</div>
	</div>
</div>
<div class="container">
<% flash.each do |name, msg| %>
	<div class="alert alert-<%= name == :notice ? "success" : "error" %>">
		<button type="button" class="close" data-dismiss="alert">&times;</button>
		<%= msg %>
	</div>
<% end %>
</div>

<%= yield %>
<%= render '/layouts/footer' %>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-39044717-1']);
  _gaq.push(['_setDomainName', 'bassemshaker.com']);
  _gaq.push(['_setAllowLinker', true]);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script></body>
</html>

app/views/main/about.html.erb
<div class="container about">
	<div class="row">
		<div id="wheel" class="span6">
    			<%= image_tag('avatar.jpg', :class => "about-avatar") %>
    			<a href="mailto:bassemreda@me.com"><%= image_tag('icons/mail.png', :class => "icon mail") %></a>
    			<a target="blank" href="https://github.com/bshakr/"><%= image_tag('icons/github.png', :class => "icon github") %></a>
    			<a target="blank" href="http://twitter.com/bshakr"><%= image_tag('icons/twitter.png', :class => "icon twitter") %></a>
    			<a target="blank" href="http://instagram.com/bassemshaker"><%= image_tag('icons/instagram.png', :class => "icon instagram") %>

		</div>
		<div class="span6">
			<h1>About Bassem</h1>
			<p>I'm a iOS and Rails <a href="http://github.com/bshakr/">developer</a>, and a self taught designer. I'm currently living in London, UK.</p>
			<p>I'm finishing my masters in Mobile Application Design in the school of Engineering and Digital Arts at the University of Kent.</p>
			<p>I started freelancing in the winter of 2010 and I love it.</p>
			<p>In January 2012 I joined Appommunity, a startup in New York that set out to build a social network to help people discover and share the different apps that they use on their mobile phones. I learned a ton on building a product. Six month later we ran out of money and shut it down.</p>
			<p>Last September I moved to the UK, and started my Masters.</p>
			<p>I'm currently building Nomad, a travel delay prediction engine.</p>
		</div>
	</div>
  <div class="row instarow">
    <% @instagram.each do |instagram| %>
    <%= image_tag instagram.images.standard_resolution.url, class: 'instapic' %>
    <% end %>
  </div>

</div>

app/views/main/home.html.erb
<% content_for :head, auto_discovery_link_tag(:atom, posts_url(format: "atom")) %>
<div class="container header">
	<div class="row">
		<div class="span6 offset1 hero-box">
			<h1>Hi. I'm Bassem.</h1>
			<h3>I'm a freelance designer & developer. I make apps for iOS and the web. You can check out my work <%= link_to 'here', work_url %>. Find out more <%=link_to 'about me', about_url%>.</h3>
		</div>
	</div>
</div>
<div class="container blog">
<% @posts.each do |post| %>
	<%= render post%>
<% end %>
</div>

app/views/posts/_post.html.erb
<article class="row">
  <div class="span7 offset1">
	  <header>
	  	<h1><%= link_to post.title, post_path(post) %></h1>
	    <p class="time">Posted on <time datetime="<%= post.published_at.as_json %>"><%= post_published_time post %></time></p>
	  </header>
	
	  <%= post.render_html %>
  </div>
</article>

app/views/posts/index.html.erb
<% content_for :head, auto_discovery_link_tag(:atom, posts_url(format: "atom")) %>

<div class="container blog">
<% @posts.each do |post| %>
	<%= render post%>
<% end %>
</div>

app/views/posts/show.html.erb
<div class="container">
  	<%= render @post%>
</div>

app/views/work/_actioncall.html.erb
<div class="work-divider2"></div>
<div class="container work-actioncall">
	<div class="row">
		<div class="span3 offset2">
			<h1><a href="mailto:bshakr@gmail.com">hire me</a></h1>
		</div>
		<div class="span4 offset2 ">
			<h1><%= link_to "more projects", work_url %></h1>
		</div>
	</div>
</div>

app/views/work/appommunity.html.erb
<div class="container">
	<section class="row">
		<%= image_tag('appommunity-hero.jpg', :class => "appommunity-hero") %>
		<div class="span5 nooun-hero-title">
			<h1 class="align-right large">Appommunity</h1>
			<h2 class="align-right">A social network for discovering great apps</h2>
			<h3 class="align-right"></h3>
		</div>
	</section>
</div>
<div class="work-divider1"></div>
<section class=" appommunity-section2">
	<div class="container">
		<div class="row">
			<%= image_tag('appommunity-review.jpg', :class => "appommunity-review") %>

			<div class="offset7 span4 expo-section2-text">
				<h2>Beautiful UI</h2>
				<h3>We went through dozens of design iterations to get the user interface just right.</h3>
			</div>
		</div>
	</div>
</section>
<div class="work-divider2"></div>
<section class=" container appommunity-section3">


	<div class="row ">

		<div class="span8 offset2">
			<h3 class="center">This project has been discontinued	.</h3>	
		</div>

	</div>


</section>

<%= render "actioncall" %>

app/views/work/egyptolution.html.erb
<div class="container">
	<section class="row">
		<%= image_tag('egyptolution-hero.jpg', :class => "egyptolution-hero") %>
		<div class="span5 nooun-hero-title">
			<h1 class="align-right large">Egyptolution</h1>
			<h2 class="align-right">Online Travel Magazine</h2>
			<h3 class="align-right"><a href="http://egyptolution.com/" target="_blank">egyptolution.com</a></h3>
		</div>
	</section>
</div>
<div class="work-divider1"></div>
<section class=" expo-section2">
	<div class="container">
		<div class="row">
			<%= image_tag('egyptolution-authors.jpg', :class => "responsive-expo") %>

			<div class="offset7 span4 expo-section2-text">
				<h2>Multi-author CMS</h2>
				<h3>Built from the grounds up for egyptolution, the site is powered by a multi-author content management system.</h3>
			</div>
		</div>
	</div>
</section>
<div class="work-divider2"></div>
<%= render "actioncall" %>

app/views/work/index.html.erb
<div class="container">
	<section class="row">
		<h1 class="span5 humongous">Portfolio</h1>
	</section>
	<section class="row work-featured">
	<div class="span12">
		<%= link_to image_tag('sva-featured.jpg', :class => "sva-featured"), :action => 'stourvalley' %>
	</div>
	</section>
	<section class="row work-featured">
	<div class="span12">
		<%= link_to image_tag('solace-featured.jpg', :class => "solace-featured"), :action => 'solace' %>
	</div>
	</section>
	<section class="row work-featured">
	<div class="span12">
		<%= link_to image_tag('weathereye-featured.jpg', :class => "weathereye-featured"), 'http://weathereye.co' %>
	</div>
	</section>

	<section class="row work-projects-row">
		<div class="span4">
			<%= link_to image_tag('nooun-preview-medium.jpg', :class => "work-preview-medium"), :action => 'nooun' %>
			<h4>Nooun</h4>
		</div>
		<div class="span4">
			<%= link_to image_tag('nyexpo-preview-medium.jpg', :class => "work-preview-medium") , :action => 'nyexpo' %>
			<h4>NY Business Expo</h4>
		</div>
		<div class="span4">
			<%= link_to image_tag('lawfirm-preview-medium.jpg', :class => "work-preview-medium") , :action => 'lawfirm' %>
			<h4>Emad Lawfirm</h4>
		</div>

	</section>

	<section class="row work-projects-row">
		<div class="span4">
			<%= link_to image_tag('egyptolution-preview-medium.jpg', :class => "work-preview-medium"), :action => 'egyptolution' %>
			<h4>Egyptolution</h4>
		</div>
		<div class="span4">
			<%= link_to image_tag('appommunity-preview-medium.jpg', :class => "work-preview-medium") , :action => 'appommunity' %>
			<h4>Appommunity</h4>
		</div>
		<div class="span4">
			<%= link_to image_tag('tia-preview-medium.jpg', :class => "work-preview-medium") , :action => 'tia' %>
			<h4>Tia Kharrat Architecture</h4>
		</div>

	</section>

</div>

app/views/work/lawfirm.html.erb
<div class="container">
	<section class="row">
		<%= image_tag('lawfirm-hero.jpg', :class => "expo-hero") %>
		<div class="span5 nooun-hero-title">
			<h1 class="align-right large">Emad Lawfirm</h1>
			<h2 class="align-right">Online home of Emad Helmy's Lawfirm</h2>
			<h3 class="align-right"><a target="_blank" href="http://emadlawfirm.com/">emadlawfirm.com</a></h3>

		</div>
	</section>
</div>
<div class="work-divider1"></div>
<section class=" expo-section2">
	<div class="container">
		<div class="row">
			<%= image_tag('lawfirm-typography.jpg', :class => "responsive-expo") %>

			<div class="offset7 span4 expo-section2-text">
				<h2>beautiful typography</h2>
				<h3>Typography is one of the most powerful design elements. It sets the tone to the message displayed.</h3>
			</div>
		</div>
	</div>
</section>
<%= render "actioncall" %>

app/views/work/nooun.html.erb
<div class="container">
	<section class="row">
		<%= image_tag('nooun-hero.jpg', :class => "nooun-hero") %>
		<div class="span4 nooun-hero-title">
			<h1 class="align-right humongous">Nooun</h1>
			<h2 class="align-right">an online magazine for women</h2>
			<h3 class="align-right"><a href="http://nooun.net/" target="_blank">nooun.net</a></h3>

		</div>
	</section>
</div>
<div class="work-divider1"></div>
<section class=" nooun-section2">
	<div class="container">
		<div class="row">
			<%= image_tag('nooun-admin.png', :class => "nooun-admin") %>

			<div class="offset7 span5 nooun-section2-text">
				<h2>bespoke site management</h2>
				<h3>nooun features a custom made management interface to allow the writers and editors to publish, change and customise every aspect of the site.	</h3>
			</div>
		</div>
	</div>
</section>
<div class="work-divider2"></div>
<div class="container">
		<div class="row">
			<h2 class="center">beautiful design</h2>
			<h3 class="center">focused on content</h3>
			<%= image_tag('nooun-article-page.jpg', :class => "nooun-article") %>
		</div>
</div>
<%= render "actioncall" %>

app/views/work/nyexpo.html.erb
<div class="container">
	<section class="row">
		<%= image_tag('expo-hero.jpg', :class => "expo-hero") %>
		<div class="span4 nooun-hero-title">
			<h1 class="align-right humongous">NY Expo</h1>
			<h2 class="align-right">New York Business Expo 2012</h2>
		</div>
	</section>
</div>
<div class="work-divider1"></div>
<section class=" expo-section2">
	<div class="container">
		<div class="row">
			<%= image_tag('responsive-expo.jpg', :class => "responsive-expo") %>

			<div class="offset7 span4 expo-section2-text">
				<h2>responsive design</h2>
				<h3>NY Business Expo features a responsive design that adapts itself to the device's width.</h3>
			</div>
		</div>
	</div>
</section>
<div class="work-divider2"></div>
<div class="container">
		<div class="row">
		<h2 class="center">a customised administration</h2>
		<h3 class="center">tailored controls designed for flexbility</h3>
		<%= image_tag('expo-admin.jpg', :class => "expo-admin") %>
	</div>
</div>
<%= render "actioncall" %>

app/views/work/solace.html.erb
<div class="container">
	<section class="row">
		<%= image_tag('solace-iphone.png', :class => "solace-hero") %>
		<div class="span4 solace-hero-title">
			<h1 class="align-right humongous">solace</h1>
			<h2 class="align-right">iPhone app that unlocks your door.</h2>
			<h3 class="align-right"><a href="http://solacecontrols.com/" target="_blank">solacecontrols.com</a></h3>
		</div>
	</section>
</div>
<div class="work-divider1"></div>
<section class=" solace-section2">
	<div class="container">
		<div class="row">
			<%= image_tag('solace-web.png', :class => "solace-web") %>

			<div class="offset7 span5 solace-section2-text">
				<h2>iPhone development</h2>
				<h3>developing the iPhone app to control RFID doors.</h3>
				<h2>marketing site</h2>
				<h3>designed and developed to showcase the iphone app features.</h3>
			</div>
		</div>
	</div>
</section>
<%= render "actioncall" %>

app/views/work/stourvalley.html.erb
<div class="container">
	<section class="row">
		<%= image_tag('stour-valley-hero.png', :class => "stour-valley-hero") %>
		<div class="span4 solace-hero-title">
			<h1 class="align-right humongous">stour valley</h1>
			<h2 class="align-right">iPhone app that guides you through Kings Wood</h2>
			<h3 class="align-right"><a href="http://stourvalleyarts.org.uk/" target="_blank">stourvalleyarts.org.uk</a></h3>
		</div>
	</section>
</div>

<%= render "actioncall" %>

app/views/work/tia.html.erb
<div class="container">
	<section class="row">
		<%= image_tag('tia-hero.jpg', :class => "tia-hero") %>
		<div class="span5 nooun-hero-title">
			<h1 class="align-right large">Tia Kharrat</h1>
			<h2 class="align-right">Architecture Portfolio</h2>
			<br/>
			<h3 class="align-right"><a href="http://tiakharrat.com/"  target="_blank">tiakharrat.com</a></h3> 
		</div>
	</section>
</div>
<%= render "actioncall" %>